server:
  port: 8081

spring:
  application:
    name: shopping-cart

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "health,info"
    jmx:
      exposure:
        include: "health,info"

  endpoint:
    info:
      enabled: true

    health:
      show-details: always